default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  min_messages: log

development:
  <<: *default
  database: web_development

test:
  <<: *default
  database: web_test

production:
  <<: *default
  database: web_production
  url: <%= ENV['DATABASE_URL'] %>
  min_messages: notice
